stages:
  - setup
  - build

prepare:
  stage: setup
  image: maven:3.3.9-jdk-8
  cache:
    key: maven
    paths:
      - ~/.m2
  script:
    - mvn dependency:resolve -B -U

mavenBuild:
  stage: test
  cache:
    key: maven
    paths:
      - ~/.m2
  artifacts:
    expire_in: 1 week
    paths:
      - ./target/wildbook-6.0.0-EXPERIMENTAL.war
  script:
    - mvn clean install -Dmaven.javadoc.skip=true
