stages:
  - setup
  - test
  - build

prepare:
  stage: setup
  image: maven:3.3.9-jdk-8
  tags:
    - docker
  cache:
    key: maven
    paths:
      - ./m2Repository
  script:
    - cp settings.xml /root/.m2/settings.xml
    - mvn dependency:resolve -B -U

test:
  stage: test
  image: maven:3.3.9-jdk-8
  tags:
    - docker
  cache:
    key: maven
    paths:
      - ./m2Repository
  dependencies:
    - prepare
  script:
    - cp settings.xml /root/.m2/settings.xml
    - mvn test -B

build:
  stage: build
  image: maven:3.3.9-jdk-8
  tags:
    - docker
  cache:
    key: maven
    paths:
      - ./m2Repository
  artifacts:
    expire_in: 1 week
    paths:
      - ./target/wildbook-6.0.0-EXPERIMENTAL.war
  dependencies:
    - test
  script:
    - cp settings.xml /root/.m2/settings.xml
    - mvn clean install -DskipTests -Dmaven.javadoc.skip=true -B
