version: "3.8"

services:

  db:
    image: postgres:13.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 60
    labels:
      - autoheal=true
    user: postgres
    volumes:
      - db-pgdata-var:/var/lib/postgresql/data
      # DB initialization scripts
      - .dockerfiles/db/initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - intranet
    ports:
      # development exposure, not exposed in production
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      WBIA_DB_NAME: "${WBIA_DB_NAME}"
      WBIA_DB_USER: "${WBIA_DB_USER}"
      WBIA_DB_PASSWORD: "${WBIA_DB_PASSWORD}"
      WILDBOOK_DB_NAME: "${WILDBOOK_DB_NAME}"
      WILDBOOK_DB_USER: "${WILDBOOK_DB_USER}"
      WILDBOOK_DB_PASSWORD: "${WILDBOOK_DB_PASSWORD}"

  wildbook:
    image: tomcat:9.0.85-jre8-temurin-jammy
    depends_on:
      db:
        condition: service_healthy
    labels:
      - autoheal=true
    volumes:
      - wildbook-var:/data/wildbook_data_dir
      - .dockerfiles/tomcat/server.xml:/usr/local/tomcat/conf/server.xml
      - .dockerfiles/tomcat/watermark.png:/usr/local/tomcat/watermark.png
      - "$WILDBOOK_BASE_DIR/webapps/:/usr/local/tomcat/webapps/"
      - "$WILDBOOK_BASE_DIR/logs/:/usr/local/tomcat/logs/"
    networks:
      - intranet
    ports:
      # FIXME: exposed for developer verification
      - "81:8080"
    environment:
      DB_USER: "${WILDBOOK_DB_USER}"
      DB_PASSWORD: "${WILDBOOK_DB_PASSWORD}"
      DB_CONNECTION_URL: "${WILDBOOK_DB_CONNECTION_URL}"
      # Admin user created on startup,
      # https://github.com/WildMeOrg/Wildbook/commit/6d65e70e43691f1b281bb76edf151e5c7cdb7403
      ADMIN_EMAIL: "${EDM_AUTHENTICATIONS_USERNAME__DEFAULT}"
      ADMIN_PASSWORD: "${EDM_AUTHENTICATIONS_PASSWORD__DEFAULT}"
      # JAVA_OPTS from old-world wildbook, which gives us 4G heap memory
      JAVA_OPTS: "-Djava.awt.headless=true -Xms4096m -Xmx4096m"

  wbia:
    # https://github.com/WildMeOrg/wildbook-ia
    image: wildme/wbia:latest
    command: ["--db-uri", "${WBIA_DB_URI}"]
    depends_on:
      db:
        condition: service_healthy
    # healthcheck:  # WBIA defines it's own health check and is already labeled for autoheal
    # labels:
    #   - autoheal=true
    volumes:
      - wbia-database-var:/data/db
      - wbia-cache-var:/cache
    networks:
      - intranet
    ports:
      - "82:5000"
    environment:
      WBIA_DB_URI: "${WBIA_DB_URI}"
      HOUSTON_CLIENT_ID: "${HOUSTON_CLIENT_ID}"
      HOUSTON_CLIENT_SECRET: "${HOUSTON_CLIENT_SECRET}"

  autoheal:
    image: willfarrell/autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AUTOHEAL_CONTAINER_LABEL: "autoheal"
      AUTOHEAL_INTERVAL: 15
      AUTOHEAL_START_PERIOD: 600
      AUTOHEAL_DEFAULT_STOP_TIMEOUT: 60
    restart: always

networks:
  intranet:

volumes:
  db-pgdata-var:
  wbia-database-var:
  wbia-cache-var:
  wildbook-var:
