name: Development Build

on:
  push:
      branches-ignore:
          - master
      tags-ignore:
          - v*
jobs:
  devops:
    name: DevOps container image build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build containers
      - name: Build containers
        run: bash devops/build.sh

      # Log into container registries
      - name: Log into Docker Hub
        run: echo "${{ secrets.WBIA_WILDMEBOT_DOCKER_HUB_TOKEN }}" | docker login -u wildmebot --password-stdin
      
      - name: Log into GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      # Push containers out to container registries
      - name: Push to GitHub Packages
        run: bash devops/publish.sh -t nightly -r docker.pkg.github.com
      
