name: Nightly

on:
  push:
    branches:
      - master
      - docker-login-secure
  schedule:
    - cron: '0 0 * * *' # Every day at midnight

jobs:
  build:
    name: Maven build and deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: |
        mvn dependency:resolve -B -U
        mvn clean install -DskipTests -Dmaven.javadoc.skip=true -B  -e -X
        mvn -B package --file pom.xml

    - name: Publish to GitHub Packages 
      if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }} 
      run: |
            mvn -B deploy
            
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
