name: Production Build

on:
  push:
      branches:
          - production

jobs:
  build:
    name: Maven build and deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8*
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 8

    - name: Build with Maven
      run: |
        mvn dependency:resolve -B -U
        mvn clean install -DskipTests -Dmaven.javadoc.skip=true -B
        mvn -B package --file pom.xml
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: wildmeorg
        password: ${{ secrets.WBIA_WILDMEBOT_DOCKER_HUB_TOKEN  }}

    - name: Build Docker image
      run: |
        docker build -t wildme/wildbook:production  -f devops/deploy/Dockerfile devops/deploy/

    - name: Push Docker image
      run: |
        docker push wildme/wildbook:production  
    # Publishing to git is disabld for Development branch
    #- name: Publish to GitHub Packages
    #if: github.event_name == 'push' 
    #run: mvn -B deploy -Dversion=development
    #env:
    #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
