name: Production Build

on:
  release:
    types: [published]


jobs:
  build:
    name: Maven build , deploy and release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8*
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 8

    - name: Build with Maven
      run: |
        mvn dependency:resolve -B -U
        mvn clean install -DskipTests -Dmaven.javadoc.skip=true -B
        mvn -B package --file pom.xml
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: wildmeorg
        password: ${{ secrets.WBIA_WILDMEBOT_DOCKER_HUB_TOKEN  }}

    - name: Build Docker image
      run: |
        docker build -t wildme/wildbook:${{ github.event.release.tag_name }}  -f devops/deploy/Dockerfile devops/deploy/

    - name: Push Docker image
      run: |
        docker push wildme/wildbook:${{ github.event.release.tag_name }}  

      
